import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import ApolloProviderWrapper from "@/components/ApolloProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"; 
import { SubscriptionProvider } from "./context/SubscriptionContext";

export const metadata: Metadata = {
  title: "CraftBot AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloProviderWrapper>
      <SubscriptionProvider> 
        <ClerkProvider>
          <html lang="en">
            <head>
              <link
                href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap"
                rel="stylesheet"
              />
            </head>
            <body className="min-h-screen flex overflow-y-scroll overflow-x-hidden">
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children} <Toaster position="bottom-center" />
              </ThemeProvider>
            </body>
          </html>
        </ClerkProvider>
      </SubscriptionProvider>
    </ApolloProviderWrapper>
  );
}
